# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_comments_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
