# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170625_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='articles_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Author'),
        ),
    ]
